/* Project Page
            * The first component contains the project name and description
            * Next, a component that will contain a list of all users assigned to the project and a button to add new users 
            * Next, The list of tickets used by this project
            * Lastly, a component that will display comments about this project, and have a form where users can type and submit new comments 

            *** The way this page is generated to be rendered could be like ***
                1) A selector is used from allProjectsSlice to grab all the info from the db about this specific project, which would be stored in a variable
                2) That variable would be accessed to fill in the Project name, project description, list of users assigned to the project, and comments pannel  
                3) The allTicketsSlice selector could take the id of the project and return all tickets info and store it in a variable here,
                    then display only those relevant to the current user/all tickets if admin
                        So i think this could be done by using the same Rows component as the dataList page 

            ***

    The components used to generate this page are found in ../components/DataItem
    Assigned users to the project, comments relating to the project, and description info about the project are all generated by their respective components.
    The reason i think it should be organized this way is because those components can be recycled when generating ticket item pages as well. 

    The components to generate the actual list of tickets a user would see on this project's page are found in ../components/DataTable
    A data table component will consist of a TitleBar component, several DataRow components, and a DataTableNavBar component. 
    The reason i think it should be organized this way is because those components can be recycled when generating the dataList view page for projects and tickets.
*/
import React, {useEffect} from 'react';
import { useSelector, useDispatch } from 'react-redux';

//Use this to call loadData in the slice on initial render
import { projects } from '../../frontend_dev_data'; 
import { loadProjectData } from './allProjectsSlice';

export default function ProjectPage(){


const dispatch = useDispatch();
dispatch(loadProjectData(projects));


return(
    <div>
        <p>test</p>
    </div>

);

};